## Tugas 2

In [ ]:
# Load data
import numpy as np
import pandas as pd
dataNB = pd.read_csv('/content/spam.csv', encoding='latin-1')
dataNB.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
# Drop 3 kolom terakhir dengan fungsi iloc
dataNB = dataNB.drop(dataNB.iloc[:,2:], axis=1)

# Definisikan nama kolom
dataNB.columns = ['Labels', 'SMS']

# Cek data
dataNB.head()

Labels                                                SMS
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# Cek Jumlah Data Per Kelas
print(dataNB['Labels'].value_counts())
print('\n')

# Cek Kelengkapan Data
print(dataNB.info())
print('\n')

# Cek Statistik Deskriptif
print(dataNB.describe())

Labels
ham     4825
spam     747
Name: count, dtype: int64


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Labels  5572 non-null   object
 1   SMS     5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB
None


       Labels                     SMS
count    5572                    5572
unique      2                    5169
top       ham  Sorry, I'll call later
freq     4825                      30


- Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,
  1. Menggunakan data spam.csv
  2. Fitur CountVectorizer dengan mengaktifkan stop_words
  3. Evaluasi hasilnya

In [ ]:
# Import library yang dibutuhkan
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# --- 1. Load dataset ---
dataNB = pd.read_csv('/content/spam.csv', encoding='latin-1')

# Drop 3 kolom terakhir
dataNB = dataNB.drop(dataNB.iloc[:, 2:], axis=1)

# Ubah nama kolom
dataNB.columns = ['Labels', 'SMS']

# --- 2. Cek data ---
print(dataNB.head())
print("\nJumlah data per kelas:")
print(dataNB['Labels'].value_counts())
print("\n")

# --- 3. Pisahkan data menjadi fitur dan label ---
X = dataNB['SMS']
y = dataNB['Labels']

# --- 4. Split data menjadi data latih dan data uji ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# --- 5. Ekstraksi fitur menggunakan CountVectorizer ---
# Aktifkan stop words bahasa Inggris
vectorizer = CountVectorizer(stop_words='english')

# Fit dan transform data latih
X_train_counts = vectorizer.fit_transform(X_train)

# Transform data uji
X_test_counts = vectorizer.transform(X_test)

# --- 6. Buat model Multinomial Naive Bayes ---
model = MultinomialNB()

# Latih model
model.fit(X_train_counts, y_train)

# --- 7. Prediksi ---
y_pred = model.predict(X_test_counts)

# --- 8. Evaluasi hasil ---
print("=== Evaluasi Model ===")
print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


  Labels                                                SMS
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

Jumlah data per kelas:
Labels
ham     4825
spam     747
Name: count, dtype: int64


=== Evaluasi Model ===
Akurasi: 0.9838565022421525

Confusion Matrix:
 [[960   6]
 [ 12 137]]

Classification Report:
               precision    recall  f1-score   support

         ham       0.99      0.99      0.99       966
        spam       0.96      0.92      0.94       149

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



- Accuracy: Persentase prediksi benar.
- Confusion Matrix: Tabel benar/salah untuk tiap kelas (ham vs spam).
- Classification Report: Menampilkan precision, recall, dan f1-score per kelas.

- Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,
  1. Menggunakan data spam.csv
  2. Fitur TF-IDF dengan mengaktifkan stop_words
  3. Evaluasi hasilnya dan bandingkan dengan hasil pada Tugas no 2.
  4. Berikan kesimpulan fitur mana yang terbaik pada kasus data spam.csv

In [ ]:
from sklearn.naive_bayes import MultinomialNB # class untuk model MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score # evaluasi model berdasarkan akurasi

# Inisiasi obyek MultinomialNB
mnb = MultinomialNB()

# Kita dapat langsung menggunakan fitur X dan label y
# hasil dari proses pembuatan data dummy

# Split data training dan testing
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=30)

# Fit model
# Label y harus dalam bentuk 1D atau (n_samples,)
mnb.fit(X_train, y_train)

# Prediksi dengan data training
y_train_pred = mnb.predict(X_train)

# Evaluasi akurasi training
acc_train = accuracy_score(y_train, y_train_pred)

# Prediksi test data
y_test_pred = mnb.predict(X_test)

# Evaluasi model dengan metric akurasi
acc_test = accuracy_score(y_test, y_test_pred)

# Print hasil evaluasi
print(f'Hasil akurasi data train: {acc_train}')
print(f'Hasil akurasi data test: {acc_test}')

Hasil akurasi data train: 0.5151105096977898
Hasil akurasi data test: 0.5173501577287066


In [ ]:
# Import library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# --- 1. Load dataset ---
dataNB = pd.read_csv('/content/spam.csv', encoding='latin-1')
dataNB = dataNB.drop(dataNB.iloc[:, 2:], axis=1)
dataNB.columns = ['Labels', 'SMS']

# --- 2. Pisahkan fitur dan label ---
X = dataNB['SMS']
y = dataNB['Labels']

# Split data train-test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# =======================================================
# MODEL 1: CountVectorizer
# =======================================================
count_vectorizer = CountVectorizer(stop_words='english')
X_train_count = count_vectorizer.fit_transform(X_train)
X_test_count = count_vectorizer.transform(X_test)

model_count = MultinomialNB()
model_count.fit(X_train_count, y_train)
y_pred_count = model_count.predict(X_test_count)

# Evaluasi
acc_count = accuracy_score(y_test, y_pred_count)
print("=== HASIL DENGAN CountVectorizer ===")
print("Akurasi:", acc_count)
print("\nClassification Report:\n", classification_report(y_test, y_pred_count))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_count))


# =======================================================
# MODEL 2: TF-IDF Vectorizer
# =======================================================
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

model_tfidf = MultinomialNB()
model_tfidf.fit(X_train_tfidf, y_train)
y_pred_tfidf = model_tfidf.predict(X_test_tfidf)

# Evaluasi
acc_tfidf = accuracy_score(y_test, y_pred_tfidf)
print("\n\n=== HASIL DENGAN TF-IDF Vectorizer ===")
print("Akurasi:", acc_tfidf)
print("\nClassification Report:\n", classification_report(y_test, y_pred_tfidf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_tfidf))

# =======================================================
# Perbandingan hasil
# =======================================================
print("\n=== PERBANDINGAN MODEL ===")
print(f"Akurasi CountVectorizer : {acc_count:.4f}")
print(f"Akurasi TF-IDF Vectorizer: {acc_tfidf:.4f}")

if acc_tfidf > acc_count:
    print("\n Kesimpulan: Model dengan TF-IDF Vectorizer memberikan hasil yang lebih baik.")
elif acc_tfidf < acc_count:
    print("\n Kesimpulan: Model dengan CountVectorizer memberikan hasil yang lebih baik.")
else:
    print("\n Kesimpulan: Kedua model memberikan hasil akurasi yang sama.")


=== HASIL DENGAN CountVectorizer ===
Akurasi: 0.9838565022421525

Classification Report:
               precision    recall  f1-score   support

         ham       0.99      0.99      0.99       966
        spam       0.96      0.92      0.94       149

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115


Confusion Matrix:
 [[960   6]
 [ 12 137]]


=== HASIL DENGAN TF-IDF Vectorizer ===
Akurasi: 0.968609865470852

Classification Report:
               precision    recall  f1-score   support

         ham       0.97      1.00      0.98       966
        spam       1.00      0.77      0.87       149

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.97      1115


Confusion Matrix:
 [[966   0]
 [ 35 114]]

=== PERBANDINGAN MODEL ===
Akurasi CountVectorizer : 0.9839
Akurasi TF-IDF V

Untuk kasus klasifikasi spam SMS pada dataset spam.csv, CountVectorizer menghasilkan performa yang lebih baik dibandingkan TF-IDF Vectorizer.